### ISSUE TITLE
GDS exiting with error code 1

### ISSUE THREAD

**Issue by jhui323444** [TinyTapeout/tt05-submission-template#2]
https://wokwi.com/projects/377874364814194689

The GDS is failing when trying to compile and I am not sure what is the issue

![image](https://github.com/TinyTapeout/tt05-submission-template/assets/65790394/1d479df5-0c99-4813-912d-e08e71ee4351)

**Comment by urish** [comment]
Closing as this being discussed on Discord: https://discord.com/channels/1009193568256135208/1009193692084580472/threads/1167760997860265994
