### ISSUE TITLE
Problems with GDS viewer

### ISSUE THREAD

**Issue by kelvinutp** [TinyTapeout/tt05-submission-template#4]
I allowed actions to run and got a success for gds and precheck, but failed the viewer. When looking for the error in log found the following:

Error: Creating Pages deployment failed
Error: HttpsError: Not found

Error: Failed to create deployment (status: 404) with build version ....

What can I do to fix it?
Will it stop me from submitting the ASIC for manufacturing?

**Comment by urish** [comment]
Hi, please follow this procedure: https://tinytapeout.com/faq/#my-github-action-is-failing-on-the-pages-part

Thanks!
